name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . --tag my-application:$(date +%s)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
      env:
        KUBECONFIG: kubeconfig.yml

  codeql-analysis:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
    
    - name: Analyze
      uses: github/codeql-action/analyze@v1
