name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --tag my-application:$(date +%s)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Configure AWS credentials from GitHub secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2  # Specify the AWS region of EKS cluster

    - name: Update kubeconfig for EKS
      run: aws eks --region eu-west-2 update-kubeconfig --name hello-world-cluster

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/

  codeql-analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
    - name: Analyze
      uses: github/codeql-action/analyze@v1
