name: Automated Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The application version to rollback to'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Update kubeconfig for EKS
      run: aws eks --region eu-west-2 update-kubeconfig --name hello-world-cluster

    - name: Rollback to a specific version
      run: kubectl set image deployment/hello-world hello-world=my-application:${{ github.event.inputs.version }} --record
